# Use lightweight Node image
FROM node:18-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy dependency files first (for caching)
COPY package*.json ./

# Install dependencies
RUN npm install 

# Copy rest of the code
COPY . .

# Expose backend port (change if needed)
EXPOSE 3000
EXPOSE 3001


# Start the app
CMD ["node", "index.js"]
